### ISSUE TITLE
Return the handlebars instance when required

### ISSUE THREAD

**Issue by diminish7** [pandastrike/panda-template#1]
Right now we are returning a function that compiles a template, but we are never exposing the `handlebars` object under the covers. That prevents us from being able to register additional helpers, or to register partials. Plus it means that the API is different than the API of `handlebars`, when really all we're trying to do is add some convenience on top of `handlebars`, but there's a shorter learning curve if the API is still the same as `handlebars`.

@dyoder Any objections?

**Comment by dyoder** [comment]
I had planned to do exactly this, so no objections. +1
